#com:
#  stu:
#    name: 小美
#    sex: 0
#    stus:
#      - 唱歌
#      - 跳舞
#      - 放冰墙
#    address:
#      ads: 河南省
#      ads2: 郑州市
#      ads3: 金水区

server:
  port: 8097
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

#配置数据源
spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  #配置映射文件的扫描
  mapper-locations: classpath:com/cj/dao/*.xml
  #配置别名的扫描
  type-aliases-package: com.cj.entity

  spring:
    thymeleaf:
      #关闭页面缓存
      cache: false